name: CLI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make build

      - name: Uploads Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: built
          path: dist/
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2.1.0
        with:
            path: /tmp
      - name: Create GitHub Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: /tmp/built
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
